### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by johnsonjh** [TI-S1500/ROMs#1]
Hi @bryanc806 

Do you have any documented status on these?

When you first posted them, I found (somewhere) that you had problems and later posted some corrected versions.

I see that at least a bit of corruption remains, for example, the following seems corrupt in `na127_nh127_corrected.bin`:

![Screenshot from 2022-05-14 03-48-15](https://user-images.githubusercontent.com/61629094/168416378-9feadfbf-701f-4910-ad76-9e93132760c5.png)

Here's the same area but rendered without full stripping the high bits:

![Screenshot from 2022-05-14 03-51-33](https://user-images.githubusercontent.com/61629094/168416518-3b6fb459-8641-478c-9ae9-56fd09eacdfe.png)

![Screenshot from 2022-05-14 03-56-26](https://user-images.githubusercontent.com/61629094/168416678-5b37bbdb-a410-4245-8380-5baec8d46886.png)

I think it's still worth it to put it up, even in the current state, as large portions of it disassemble cleanly, and I looked at them more than a few times during the RE process:

![Screenshot from 2022-05-14 03-59-48](https://user-images.githubusercontent.com/61629094/168416852-669a2fea-6199-49fe-993b-466aa5d305f4.png)

**Comment by bryanc806** [comment]
hmm... that's strange.  I would expect bit errors, but presumably the message is 'break detect(ed)', but the number of characters does not make sense assuming the null termination is in the correct spot.

I pulled the chips out tonight and re-read them in my eprom programmer and they match what I had done earlier.  Since these are for the comm processor, I presume I would see issues with either it's self-test or configuring of the multidrop or v.35 cards.

Maybe a good tactic would be to cause the code to emit one of the messages in question.

**Comment by bryanc806** [comment]
I think I had a better idea to test the rom integrity:  In the extended tests, there is a ROM CRC check.  I can burn a rom with a single bit changed and see if this fails.  If it does, then presumably the rom integrity is good, but either my eprom programmer (TL866-II) can't read it correctly, or there is something that we don't understand about the code.

**Comment by johnsonjh** [comment]
No rush at all.

In this particular segment, it appears to me, at least at a glance, that the strings "pattern", "interrupt", "baud rate", and "Multicast" contain errors.

There are several areas in the dump that look similar ... all corrupted strings appear to be closely clustered together, and there were a few sections where my initial disassembly attempts produced implausible code.

**Comment by johnsonjh** [comment]
It's also quite possible these strings are correct, since most of TI configuration is performed using a 7O1 (or 7E1) serial console ... so the CRC check seems the best way to go.

If the dumps are indeed correct, this does (slightly) complicate automatic detection of strings during disassembly, but, knowing for sure would be "a nice to know."

**Comment by bryanc806** [comment]
I was able to do some tests tonight on the NH127/NH127 EPROM sockets.

I programmed a separate EEPROM with the contents I read back from the NH127 chip (labeled 2561148-0004).  Placing this in the socket worked fine.  The console output at boot was normal.

Then, I changed a single bit in the rom and tried that.  I got the following:


```
Slot C CPU TESTING SYSTEM:

Slot 8 CPO SELF TESTS FAILED
Slot 9 SPC passed
Slot C CPU 
           *** WARNING No. 0060
           Parity map corrupted or not initialized
           -- Default map created
           passed

Global ARB passed

D=Default load, M=Menu load, R=Retest, E=Extended tests :e


Slot C CPU TESTING SYSTEM:

Slot 8 SELF TESTS FAILED
Slot 9 SPC (TIAU 00002561080-0001 AW) passed
Slot C CPU (TIAU 00002561080-0001 AW)
```

For the record, the change was:

```
$ cmp -bl 2561148_1_bit_corruption_test.bin 2561148_1.bin 
  958 106 F    105 E
```

e.g. a minor change to ASCII text near the top of the ROM.  In the combined rom, the text 'TEXAS INSTRUMENTS DIAGNOSTIC MONITOR' became 'TFXAS INSTRUMENTS DIAGNOSTIC MONITOR'

**Comment by johnsonjh** [comment]
@bryanc806 thanks!

I'll consider that enough confirmation to close this out.

It seems strange there is "noise" in the high bits of the strings, but, if that is how it is, I can't argue with it.

It's going to make a readable (ASCII) disassembly of the ROMS a bit more involved.  What I'll likely do is just convert these strings to the pure ASCII 7-bit form for the purposes of readability when I get around to doing a disassembly.

Thanks for checking!
